In [1]:
import pandas as pd
import optimization as op
import numpy as np

In [2]:
df = pd.read_csv('train.csv')
df.drop('index', axis = 1, inplace = True)

In [3]:
x = df.drop('target', axis = 1).to_numpy()
y = df.target.to_numpy().reshape(-1,1)

In [4]:
op.gradient_boost_optimizer(x, y, 0.001)

array([[ 0.25056896],
       [ 0.61282736],
       [ 0.28919794],
       [ 0.58031177],
       [ 0.08845659],
       [ 0.65237018],
       [ 0.58871275],
       [ 0.43314285],
       [ 0.83147397],
       [ 0.60985282],
       [ 0.39206632],
       [ 0.91421709],
       [ 0.15197541],
       [ 0.73135113],
       [ 0.2628831 ],
       [ 0.96307106],
       [ 0.3511879 ],
       [ 0.74881838],
       [ 0.64535911],
       [-0.06847012],
       [ 0.71990385],
       [ 0.52494359],
       [ 0.44938941],
       [ 0.89342395],
       [ 1.13670226],
       [ 0.12290982],
       [ 0.92458788],
       [ 0.56761253],
       [ 0.20794838],
       [ 0.2289711 ],
       [ 0.39769239],
       [ 0.60500649],
       [ 0.94662955],
       [ 0.84029946],
       [ 0.55895522],
       [ 0.63145729],
       [ 0.83037515],
       [ 0.6422941 ],
       [ 0.16931149],
       [ 0.03084394],
       [ 0.90791239],
       [ 0.5409792 ],
       [ 0.47903443],
       [ 0.51540745],
       [ 0.7686343 ],
       [ 0

In [5]:
op.mathematical_optimization(x,y)

array([[-1119092.11327703],
       [ -601879.20877484],
       [  383414.07370234],
       [-1498304.95645432],
       [  175133.13977337],
       [-1171520.29110373],
       [ -286468.67196992],
       [  -88777.87220853],
       [-2110255.9009189 ],
       [ -198945.108026  ],
       [  153721.80524399],
       [  729137.6228248 ],
       [ -113788.83298743],
       [  919534.42404247],
       [  559513.39881526],
       [ 1060105.69075759],
       [ 2402587.42803763],
       [  137207.60020999],
       [ 2506593.34209381],
       [ -119043.31630486],
       [-1520844.79869512],
       [  509627.41319828],
       [ 1542489.16874853],
       [ 1793212.51585271],
       [  119104.2062619 ],
       [  392426.65576187],
       [ 1354387.70162666],
       [-1502747.74407434],
       [  230507.21975581],
       [  156468.05571456],
       [ 1778365.3970567 ],
       [  977508.00347202],
       [  583481.84117353],
       [-2129101.53685998],
       [   80865.14794558],
       [ 2603663.439

In [7]:
op.stohastic_gradient_boost_optimizer(x,y, 0.001)

array([[ 0.83297349],
       [ 0.43142645],
       [ 0.47201122],
       [ 0.40531007],
       [ 0.39517133],
       [ 0.55469482],
       [ 0.24866113],
       [ 0.69463925],
       [ 0.47632524],
       [ 0.46601795],
       [ 0.88923931],
       [ 0.57260844],
       [ 0.3307752 ],
       [ 0.41383517],
       [ 0.200425  ],
       [ 0.8094441 ],
       [ 0.70831737],
       [ 0.5211611 ],
       [ 0.4293582 ],
       [-0.06188825],
       [ 0.47733025],
       [-0.00690692],
       [ 0.76131941],
       [ 0.0145396 ],
       [ 1.21295999],
       [ 0.2888213 ],
       [ 0.67488066],
       [ 0.775131  ],
       [ 0.76082982],
       [ 0.80342765],
       [ 0.96750974],
       [ 0.52575279],
       [ 0.47540838],
       [ 0.31338755],
       [ 0.82677786],
       [ 0.58639981],
       [ 0.84059788],
       [ 0.84042804],
       [ 0.89232383],
       [ 0.76647595],
       [ 0.50075852],
       [ 0.23045919],
       [ 0.93179729],
       [ 1.02862048],
       [ 0.87800561],
       [ 0